//! Pins for writing a partition: idempotent files, and a workspace config that is **merged**.
//! 写下一次拆分的钉子：幂等的文件，以及**被合并**的工作区配置。

use std::fs;
use std::path::{Path, PathBuf};

use super::write_partition;
use crate::build_method::crate_plan::{PlannedCrate, PlannedMount};

/// A throwaway workspace root.
/// 一个一次性工作区根。
fn workspace(label: &str) -> PathBuf {
    static NEXT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    let sequence = NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let root = std::env::temp_dir()
        .join("nichlink-scratch")
        .join(module_path!().replace("::", "-"))
        .join(format!(
            "nichlink-write-{label}-{}-{sequence}",
            std::process::id()
        ));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(&root).expect("workspace root");
    root
}

/// One planned crate, with the bytes the planner would have produced.
/// 一个已规划的 crate，带着规划器会产出的那些字节。
fn planned(root: &Path) -> PlannedCrate {
    PlannedCrate {
        name: "widgets".to_owned(),
        package: "myapp-widgets".to_owned(),
        namespace: "myapp".to_owned(),
        directory: root.join("myapp-widgets"),
        subtrees: vec!["control::object".to_owned()],
        ancestors: Vec::new(),
        mounts: vec![PlannedMount {
            module_path: "control::object::button".to_owned(),
            source: "control/object/button/button.rs".to_owned(),
            spelling: "../../../../host/src/control/object/button/button.rs".to_owned(),
        }],
        remap: vec![("../../../../host/src/".to_owned(), String::new())],
        // The bytes carry the marker the real generator writes: a revert tells its own work from a
        // hand-written package by that line, so a fixture without it is not a ghost.
        // 这些字节带着真生成器写下的那枚标记：撤回靠那一行把自己的产物与手写的包区分开，因此没有它的夹具不是幽灵。
        lib_rs: "//! Generated by NichLink: a fragment crate.\npub const NICHLINK_NAMESPACE: &str = \"myapp\";\n".to_owned(),
        build_rs: "//! Generated by NichLink: build the fragment.\nfn main() {}\n".to_owned(),
        cargo_toml: "# Generated by NichLink: the dependencies are the host's.\n[package]\nname = \"myapp-widgets\"\npublish = false\n".to_owned(),
        config_patch: String::new(),
    }
}

/// The three files land with the planned bytes, and a second pass changes nothing — a partition is
/// something you commit, so re-running it must not produce a diff.
/// 三份文件带着规划好的字节落地，而第二遍什么都不改——拆分是要提交的东西，因此重跑不能产生 diff。
#[test]
fn writing_is_idempotent() {
    let root = workspace("idempotent");
    let planned = vec![planned(&root)];
    let first = write_partition(&root, None, &planned, None).expect("the first pass writes");
    assert_eq!(
        first.files,
        vec![
            "myapp-widgets/Cargo.toml".to_owned(),
            "myapp-widgets/build.rs".to_owned(),
            "myapp-widgets/src/lib.rs".to_owned(),
        ],
        "all three files, named relative to the workspace root"
    );
    assert!(first.config_changed, "the config did not exist yet");
    let lib = root.join("myapp-widgets/src/lib.rs");
    assert!(
        fs::read_to_string(&lib)
            .expect("written")
            .contains("pub const NICHLINK_NAMESPACE"),
        "the planned bytes landed"
    );

    let before = fs::read_to_string(root.join(".cargo/config.toml")).expect("config");
    let second = write_partition(&root, None, &planned, None).expect("the second pass writes");
    assert!(
        !second.config_changed,
        "every entry is already there, so the file is untouched"
    );
    assert_eq!(
        fs::read_to_string(root.join(".cargo/config.toml")).expect("config"),
        before,
        "no duplicate entries"
    );
    assert!(
        fs::read_to_string(root.join("myapp-widgets/src/lib.rs"))
            .expect("lib")
            .contains("pub const NICHLINK_NAMESPACE"),
        "and a second pass did not touch them"
    );
    let _ = fs::remove_dir_all(&root);
}

/// A config the user already maintains keeps **everything** else, and gains only the missing entries.
/// 用户已经在维护的 config 保留**其余一切**，只多出缺少的那些条目。
#[test]
fn an_existing_workspace_config_is_merged_not_replaced() {
    let root = workspace("merged");
    fs::create_dir_all(root.join(".cargo")).expect("config dir");
    fs::write(
        root.join(".cargo/config.toml"),
        "# the maintainer's own config\n[build]\nrustflags = [\"-C\", \"target-cpu=native\"]\n\n\
         [net]\ngit-fetch-with-cli = true\n",
    )
    .expect("config");
    let planned = vec![planned(&root)];
    let written = write_partition(&root, None, &planned, None).expect("the entries merge in");
    assert!(written.config_changed);
    let config = fs::read_to_string(root.join(".cargo/config.toml")).expect("config");
    for kept in [
        "# the maintainer's own config",
        "rustflags = [\"-C\", \"target-cpu=native\", \"--remap-path-prefix=../../../../host/src/=\"]",
        "[net]",
        "git-fetch-with-cli = true",
    ] {
        assert!(config.contains(kept), "kept `{kept}`: {config}");
    }
    let _ = fs::remove_dir_all(&root);
}

/// A `rustflags` this action cannot merge into is **refused by name**, with the lines to add by hand:
/// blindly rewriting a file the user maintains is how a tool eats somebody's configuration.
/// 本动作无法合并的 `rustflags` 会被**点名拒绝**，并给出该手写上去的那几行：盲目重写用户维护的文件，正是
/// 一件工具吃掉别人配置的方式。
#[test]
fn an_unmergeable_config_is_refused_with_the_lines_to_add() {
    let root = workspace("unmergeable");
    fs::create_dir_all(root.join(".cargo")).expect("config dir");
    fs::write(
        root.join(".cargo/config.toml"),
        "[build]\nrustflags = [\n    \"-C\",\n    \"target-cpu=native\",\n]\n",
    )
    .expect("config");
    let refused = write_partition(&root, None, &[planned(&root)], None).expect_err("refused");
    assert!(
        refused.contains("--remap-path-prefix=../../../../host/src/=")
            && refused.contains("by hand"),
        "the refusal carries the lines to add: {refused}"
    );
    assert!(
        !root.join("myapp-widgets/src/lib.rs").exists(),
        "the files are not written when the config cannot be made sound"
    );
    let _ = fs::remove_dir_all(&root);
}

/// Taking a partition back removes the packages this action created and its config entries — and a
/// second revert changes nothing.
/// 撤回一次拆分：删掉本动作创建的包与它加进配置的条目——第二遍什么都不改。
#[test]
fn reverting_takes_back_exactly_this_actions_work() {
    let root = workspace("revert");
    let planned = vec![planned(&root)];
    write_partition(&root, None, &planned, None).expect("the partition writes");
    assert!(root.join("myapp-widgets/src/lib.rs").exists());

    let reverted = super::revert_partition(&root, None, &planned, None).expect("the revert runs");
    assert_eq!(
        reverted.files,
        vec!["myapp-widgets".to_owned()],
        "the package directory is what is removed"
    );
    assert!(!root.join("myapp-widgets").exists(), "and it is gone");
    assert!(
        !root.join(".cargo/config.toml").exists(),
        "a config that was only this action's shell goes with it"
    );

    let again =
        super::revert_partition(&root, None, &planned, None).expect("the second revert runs");
    assert!(again.files.is_empty() && !again.config_changed, "{again:?}");
    let _ = fs::remove_dir_all(&root);
}

/// A directory this action did **not** create is refused by name and left exactly as it is: the
/// alternative is a tool deleting somebody's package because it sits where a ghost would.
/// 本动作**没有**创建的目录会被点名拒绝并原样留下：另一种做法是工具删掉别人的包，只因为它躺在幽灵会在的位置。
#[test]
fn a_package_without_the_marker_is_never_removed() {
    let root = workspace("hand-written");
    let planned = vec![planned(&root)];
    fs::create_dir_all(root.join("myapp-widgets/src")).expect("dirs");
    fs::write(
        root.join("myapp-widgets/Cargo.toml"),
        "[package]\nname = \"myapp-widgets\"\n# a package somebody wrote by hand\n",
    )
    .expect("manifest");
    let refused = super::revert_partition(&root, None, &planned, None).expect_err("refused");
    assert!(
        refused.contains("Generated by NichLink") && refused.contains("way forward"),
        "the refusal names the missing marker and the way forward: {refused}"
    );
    assert!(
        root.join("myapp-widgets/Cargo.toml").exists(),
        "and the package is untouched"
    );
    let _ = fs::remove_dir_all(&root);
}

/// The config keeps everything that is not ours: other keys, other flags, other sections.
/// 配置保留一切不属于我们的东西：别的键、别的旗标、别的节。
#[test]
fn reverting_the_config_keeps_everything_that_is_not_ours() {
    let root = workspace("revert-merge");
    fs::create_dir_all(root.join(".cargo")).expect("config dir");
    fs::write(
        root.join(".cargo/config.toml"),
        "[build]\nrustflags = [\"-C\", \"target-cpu=native\"]\n\n[net]\ngit-fetch-with-cli = true\n",
    )
    .expect("config");
    let planned = vec![planned(&root)];
    write_partition(&root, None, &planned, None).expect("the entries merge in");
    super::revert_partition(&root, None, &planned, None).expect("the entries come back out");
    let config = fs::read_to_string(root.join(".cargo/config.toml")).expect("config");
    assert!(
        config.contains("rustflags = [\"-C\", \"target-cpu=native\"]"),
        "the maintainer's own flags are exactly as they were: {config}"
    );
    assert!(
        config.contains("git-fetch-with-cli = true") && !config.contains("remap-path-prefix"),
        "and nothing of ours is left: {config}"
    );
    let _ = fs::remove_dir_all(&root);
}

/// The workspace manifest comes back out exactly as it went in, and a partition without an enclosing
/// workspace leaves no member list behind at all (audit `M7`, P3.5).
/// 工作区清单原样回来，而没有外层工作区的拆分根本不会留下成员清单（审计 `M7`，P3.5）。
#[test]
fn the_workspace_manifest_is_edited_only_when_there_is_a_workspace() {
    let root = workspace("members");
    fs::write(
        root.join("Cargo.toml"),
        "[workspace]\nresolver = \"3\"\nmembers = [\"host\"]\n",
    )
    .expect("the workspace manifest");
    let widgets = vec![planned(&root)];

    let written = write_partition(&root, Some(&root), &widgets, None).expect("writes");
    assert!(written.members_changed, "the generated package is admitted");
    let manifest = fs::read_to_string(root.join("Cargo.toml")).expect("the manifest");
    assert!(
        manifest.contains("members = [\"host\", \"myapp-widgets\"]"),
        "the entry is added to the list that was there: {manifest}"
    );

    let reverted = super::revert_partition(&root, Some(&root), &widgets, None).expect("reverts");
    assert!(reverted.members_changed, "the package is taken back out");
    assert_eq!(
        fs::read_to_string(root.join("Cargo.toml")).expect("the manifest"),
        "[workspace]\nresolver = \"3\"\nmembers = [\"host\"]\n",
        "and the manifest is what it was"
    );

    // No workspace: the packages are standalone siblings, so there is no list to maintain.
    // 没有工作区：这些包是彼此独立的同级包，因此没有清单要维护。
    let standalone = workspace("standalone-members");
    fs::write(
        standalone.join("Cargo.toml"),
        "[workspace]\nresolver = \"3\"\nmembers = [\"host\"]\n",
    )
    .expect("the manifest");
    let written =
        write_partition(&standalone, None, &[planned(&standalone)], None).expect("writes");
    assert!(
        !written.members_changed,
        "a partition with no enclosing workspace leaves the list alone"
    );
    assert_eq!(
        fs::read_to_string(standalone.join("Cargo.toml")).expect("the manifest"),
        "[workspace]\nresolver = \"3\"\nmembers = [\"host\"]\n"
    );
    let _ = fs::remove_dir_all(&root);
    let _ = fs::remove_dir_all(&standalone);
}

/// The release shape writes the package's own files, and the same revert takes it back.
/// 发布形状写下包自己的文件，而同一个撤回把它收回来（审计 `M7`，§M7.42）。
#[test]
fn the_release_shape_carries_its_sources_and_reverts() {
    let root = workspace("release");
    let planned = planned(&root);
    let source = root.join("src/panel/frame/widget/widget.rs");
    fs::create_dir_all(source.parent().expect("a parent")).expect("the host's sources");
    fs::write(&source, "// the host's face\n").expect("the host's face");
    let release = vec![crate::build_method::crate_release::ReleasePackage {
        package: planned.package.clone(),
        directory: planned.directory.clone(),
        cargo_toml: "# Generated by NichLink\n[package]\nname = \"myapp-widgets\"\n".to_owned(),
        lib_rs: "//! Generated by NichLink\n".to_owned(),
        build_rs: "//! Generated by NichLink\nfn main() {}\n".to_owned(),
        copies: vec![
            (
                source.clone(),
                "src/panel/frame/widget/widget.rs".to_owned(),
            ),
            (root.join("add_crates.rs"), "add_crates.rs".to_owned()),
        ],
    }];
    fs::write(root.join("add_crates.rs"), "// the declaration\n").expect("the declaration");

    let written = super::write_release(&root, None, &release).expect("the release shape writes");
    assert!(
        written.files.len() >= 5,
        "three generated files and two copies: {:?}",
        written.files
    );
    let copied = planned.directory.join("src/panel/frame/widget/widget.rs");
    assert_eq!(
        fs::read_to_string(&copied).expect("the copied face"),
        "// the host's face\n",
        "the copy is the host's bytes"
    );
    assert!(planned.directory.join("add_crates.rs").is_file());
    // No workspace was given, so no member list and no config were touched.
    assert!(!written.members_changed);
    assert!(!written.config_changed);

    let directory = planned.directory.clone();
    let reverted = super::revert_partition(&root, None, &[planned], None).expect("the revert runs");
    assert!(!directory.exists(), "{reverted:?}");
    let _ = fs::remove_dir_all(root);
}

/// A shape is never written over the other one silently (audit `M7`, §M7.42).
/// 一个形状绝不静默地盖过另一个形状（审计 `M7`，§M7.42）。
#[test]
fn writing_one_shape_over_the_other_is_refused_by_name() {
    let root = workspace("shape-guard");
    let directory = root.join("myapp-widgets");
    fs::create_dir_all(&directory).expect("the package directory");
    fs::write(
        directory.join("Cargo.toml"),
        "[package]\nname = \"myapp-widgets\"\n\n[package.metadata.nichlink]\nshape = \"release\"\n",
    )
    .expect("a release-shaped manifest");

    // The development writer may not overwrite a release-shaped package: both shapes plan the same
    // directories, so a silent replacement would leave a build script reading sources that are gone.
    // 开发写入方不得覆盖发布形状的包：两个形状规划同一批目录，静默替换会留下一个读不到源码的构建脚本。
    let refused = super::guard_shape(&[directory.as_path()], false).expect_err("refused");
    assert!(
        refused.contains("written as the release shape") && refused.contains("--revert"),
        "the refusal names both shapes and the way through: {refused}"
    );
    // The shape it already is writes over itself without complaint.
    // 它本来就是的那个形状可以照常覆盖自己。
    assert!(super::guard_shape(&[directory.as_path()], true).is_ok());
    // A directory that is not there yet is nobody's shape.
    // 还不存在的目录不属于任何形状。
    assert!(super::guard_shape(&[root.join("absent").as_path()], false).is_ok());
    let _ = fs::remove_dir_all(&root);
}
