//! Generated by XiRang: build this fragment out of its own sources.
//! 由 XiRang 生成：从它自己的源码构建这个碎片。

fn main() {
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=add_crates.rs");
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    xirang_toolchain::build_method::run_for_partition(
        root,
        &out,
        "xirang-example-partitioned-button",
        Some("control"),
        false,
    )
    .expect("xirang");
}
