//! Generated by NichLink: build this fragment out of the host's sources.
//! 由 NichLink 生成：从宿主的源码构建这个碎片。

fn main() {
    println!("cargo:rerun-if-changed=/home/nich/Moirai_N3/nichlink/examples/partitioned-button/host/src");
    println!("cargo:rerun-if-changed=/home/nich/Moirai_N3/nichlink/examples/partitioned-button/host/add_crates.rs");
    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    nichlink_toolchain::build_time::run_for_partition(
        std::path::Path::new("/home/nich/Moirai_N3/nichlink/examples/partitioned-button/host"),
        &out,
        "nichlink-example-partitioned-button",
        Some("control"),
        false,
    )
    .expect("nichlink");
}
