//! Generated by NichLink: compile one package of a host's registration tree as published sources.
//! Do not edit — the declaration lives in this package's `add_crates.rs`.
//! 由 NichLink 生成：把宿主注册树的一个包当作已发布的源码来编译。请勿手工修改——声明住在本包的
//! `add_crates.rs` 里。

pub const NICHLINK_NAMESPACE: &str = "nichlink-example-partitioned-button";

include!(concat!(env!("OUT_DIR"), "/generated_lib.rs"));
