//! The top-level pass that assembles the generated lib.
//! 组装生成 lib 的顶层流程。
//!
//! `render_lib` writes the fixed preamble, the object aliases, the module tree,
//! its IDE shadows, and the build-time static plan in the order rustc requires;
//! the recursion itself and the child emitters live in the sibling modules.
//! `render_lib` 按 rustc 要求的顺序写出固定前言、对象别名、模块树、其 IDE 影子
//! 与构建期静态计划；递归本身与各子发射器位于同级模块。

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use super::aliases::{registry_path, render_object_aliases};
use super::ide::render_ide_shadows;
use super::tree::render_nodes;
use crate::diagnostics::BuildDiagnostics;
use crate::registry_syntax::GraftSyntax;
use crate::static_plan::StaticFaceRecord;
use crate::{Node, SourceScope};

pub(crate) fn render_lib(
    src: &Path,
    nodes: &[Node],
    errors: &BuildDiagnostics,
    demo_errors: &BuildDiagnostics,
    scope: &SourceScope,
    static_faces: &[StaticFaceRecord],
    grafts: &[GraftSyntax],
) -> String {
    let mut output = String::from(
        "// @generated by build.rs; do not edit.\n// 由 build.rs 生成，请勿手工修改。\n\n",
    );
    let registry = registry_path();
    render_object_aliases(&mut output, src, nodes);
    let ide_shadows = render_nodes(&mut output, src, scope, nodes);
    render_ide_shadows(&mut output, &ide_shadows);
    output.push_str(&format!("\npub use {registry}::*;\n"));
    output.push_str(&format!(
        "\n#[doc(hidden)]\npub static BUILTIN_STATIC_FACES: &[{registry}::StaticFace] = &[\n",
    ));
    for face in static_faces {
        writeln!(output, "    {registry}::StaticFace::new({registry}::NodeId::from_raw({:?}), {registry}::NodeId::from_raw({:?}), {}),", face.id.into_bytes(), face.parent.into_bytes(), face.owns_registry).unwrap();
    }
    output.push_str("];\n");
    let modules = static_faces
        .iter()
        .map(|face| (face.id, face.module.as_str()))
        .collect::<BTreeMap<_, _>>();
    output.push_str("\n// Registration rules are consumed by const evaluation only.\n// 注册规则只参与常量求值，不进入发布态数据。\n");
    for face in static_faces {
        let rule = modules.get(&face.parent).map_or_else(
            || format!("{registry}::RegistrationRule::ANY"),
            |parent| format!("{parent}::REGISTRATION.registry_rule"),
        );
        writeln!(
            output,
            "const _: () = {registry}::assert_static_registration({rule}, {}::REGISTRATION);",
            face.module
        )
        .unwrap();
    }
    output.push_str(&format!(
        "\n#[doc(hidden)]\npub static BUILTIN_GRAFT_CUTS: &[{registry}::StaticGraftCut] = &[\n",
    ));
    for graft in grafts {
        // A typed cut is emitted verbatim, so the compiler resolves the Rust
        // expressions the author wrote instead of a selector string. A string
        // cut keeps the previous form, with a range split into `new_range` from
        // the two endpoint fields — never by re-splitting the path text, which
        // would cut a path that literally contains `" to "` in half.
        // 类型化切口原样发射，编译器因此解析作者写的 Rust 表达式，而不是选择器
        // 字符串。字符串切口保持原有形式，区间用两个端点字段拆成 `new_range`——绝不
        // 重新拆分路径文本，否则字面含有 `" to "` 的路径会被拦腰截断。
        let constructor = match &graft.expressions {
            Some(expressions) => match &expressions.cut_end {
                Some(end) => format!(
                    "{registry}::StaticGraftCut::from_id_range({}, {}, {}, {})",
                    expressions.cut, end, expressions.graft, graft.full
                ),
                None => format!(
                    "{registry}::StaticGraftCut::from_ids({}, {}, {})",
                    expressions.cut, expressions.graft, graft.full
                ),
            },
            None => match &graft.cut_end {
                Some(end) => format!(
                    "{registry}::StaticGraftCut::new_range({:?}, {end:?}, {:?}, {})",
                    graft.cut, graft.graft, graft.full
                ),
                None => format!(
                    "{registry}::StaticGraftCut::new({:?}, {:?}, {})",
                    graft.cut, graft.graft, graft.full
                ),
            },
        };
        writeln!(output, "    {constructor},").unwrap();
    }
    output.push_str("];\n\n");
    // The host may have `#![warn(missing_docs)]` on, and it cannot edit this
    // generated file — so the raw static stays hidden plumbing the way
    // `BUILTIN_STATIC_FACES`/`BUILTIN_GRAFT_CUTS` do, while the two functions a
    // host actually calls carry the docs.
    // 宿主可能开着 `#![warn(missing_docs)]`，而它无法编辑这份生成文件——因此裸静态量像
    // `BUILTIN_STATIC_FACES`/`BUILTIN_GRAFT_CUTS` 一样保持为隐藏管道，而宿主真正调用的两个
    // 函数带上文档。
    output.push_str(&format!(
        "#[doc(hidden)]\npub static BUILTIN_STATIC_PLAN: {registry}::StaticPlan = {registry}::StaticPlan::with_grafts(BUILTIN_STATIC_FACES, BUILTIN_GRAFT_CUTS);\n\n"
    ));
    output.push_str(&format!(
        "/// The release-time static plan this build produced: the enabled faces plus their graft cuts.\n\
         /// 本次构建产出的发布态静态计划：启用的注册面加上它们的 graft 切口。\n\
         pub const fn builtin_static_plan() -> &'static {registry}::StaticPlan {{ &BUILTIN_STATIC_PLAN }}\n"
    ));
    output.push_str(
        "\n/// Every registration this build enabled, in tree order, as owned snapshots.\n\
         /// 本次构建启用的每一条注册，按树序，以拥有型快照给出。\n\
         pub fn registrations() -> Vec<RegistrationInfo> {\n    vec![\n",
    );
    for face in static_faces {
        writeln!(output, "        {}::REGISTRATION,", face.module).unwrap();
    }
    output.push_str("    ]\n        .into_iter()\n        .collect()\n}\n");
    if !errors.is_empty() {
        output.push('\n');
        writeln!(output, "compile_error!({:?});", errors.render()).unwrap();
    }
    if !demo_errors.is_empty() {
        output.push_str("\n#[cfg(feature = \"compile_error_demo\")]\n");
        writeln!(output, "compile_error!({:?});", demo_errors.render()).unwrap();
    }
    output
}

#[cfg(test)]
mod tests {
    use super::render_lib;
    use crate::Node;
    use crate::SourceScope;
    use crate::diagnostics::BuildDiagnostics;
    use crate::registry_syntax::GraftSyntax;
    use crate::renderer::test_support::{temporary_directory, write_registry};
    use nichlink::registry_core::syntax::SyntaxLocation;
    use std::fs;

    #[test]
    fn generated_static_plan_owns_build_time_graft_selectors() {
        let root = temporary_directory("static-graft-plan");
        let output = render_lib(
            &root,
            &[],
            &BuildDiagnostics::default(),
            &BuildDiagnostics::default(),
            &SourceScope {
                roots: None,
                reason: "test",
            },
            &[],
            &[GraftSyntax {
                cfg: None,
                cut: "root/control/button".to_owned(),
                cut_end: None,
                graft: "button_fast".to_owned(),
                full: false,
                location: SyntaxLocation { line: 3, column: 5 },
                expressions: None,
            }],
        );

        assert!(output.contains("StaticPlan::with_grafts"));
        assert!(output.contains("StaticGraftCut::new(\"root/control/button\", \"button_fast\""));
        assert!(!output.contains("pub fn builtin_graft_plan"));
        fs::remove_dir_all(root).expect("temporary fixture cleanup");
    }

    /// A string path that literally contains `" to "` is one cut, and the
    /// renderer must not hand its halves to `new_range`. This is the consumer
    /// side of the range-as-data change: the parser keeps `cut_end` empty for
    /// such a path, and the renderer reads that field instead of the path text.
    /// 字面含有 `" to "` 的字符串路径是一条切口，渲染器绝不能把它的两半交给
    /// `new_range`。这是“区间即数据”改动的消费侧：解析器对这类路径让 `cut_end`
    /// 保持为空，渲染器读取该字段而不是路径文本。
    #[test]
    fn a_path_containing_the_range_word_is_rendered_as_one_cut() {
        let root = temporary_directory("string-cut-to-word");
        let entries = crate::registry_syntax::graft_entries(
            r#"nichlink::static_graft_plan!(FRAMEWORK, cut "root/a to b" graft "g");"#,
        )
        .expect("declaration parses");
        let output = render_lib(
            &root,
            &[],
            &BuildDiagnostics::default(),
            &BuildDiagnostics::default(),
            &SourceScope {
                roots: None,
                reason: "test",
            },
            &[],
            &entries,
        );

        assert!(
            output.contains(r#"StaticGraftCut::new("root/a to b", "g", false)"#),
            "the whole path must stay one cut: {output}"
        );
        assert!(
            !output.contains("new_range"),
            "a literal path is not a range: {output}"
        );
        fs::remove_dir_all(root).expect("temporary fixture cleanup");
    }

    /// Faces load as real modules through `#[path]`, never as copies. A leaf
    /// face keeps its own module name so the public path is unchanged; a face
    /// that owns child registries must also be their container, so it loads
    /// into a same-named child module and re-exports.
    /// 注册面通过 `#[path]` 以真实模块载入，绝不是副本。叶子面保留自身模块名，
    /// 公开路径不变；拥有子注册机的面必须同时充当容器，因此载入同名子模块再
    /// 重导出。
    #[test]
    fn faces_load_by_path_without_copies_or_injected_constants() {
        let root = temporary_directory("path-loaded-faces");
        let control = root.join("control/control.rs");
        let button = root.join("control/object/button/button.rs");
        write_registry(&control, "root_object", "Control", "crate::ROOT_NODE_ID");
        write_registry(
            &button,
            "control_object",
            "Button",
            "crate::control::NODE_ID",
        );
        let nodes = vec![Node {
            name: "control".to_owned(),
            file: Some(control.clone()),
            children: vec![Node {
                name: "object".to_owned(),
                file: None,
                children: vec![Node {
                    name: "button".to_owned(),
                    file: Some(button.clone()),
                    children: Vec::new(),
                }],
            }],
        }];

        let output = render_lib(
            &root,
            &nodes,
            &BuildDiagnostics::default(),
            &BuildDiagnostics::default(),
            &SourceScope {
                roots: None,
                reason: "test",
            },
            &[],
            &[],
        );

        let control_path = control.to_string_lossy().replace('\\', "/");
        let button_path = button.to_string_lossy().replace('\\', "/");
        assert!(
            output.contains(&format!("#[path = {control_path:?}]")),
            "folder face must load its real file: {output}"
        );
        assert!(
            output.contains(&format!("#[path = {button_path:?}]")),
            "leaf face must load its real file: {output}"
        );
        assert!(
            !output.contains("include!("),
            "faces must be modules, not included copies: {output}"
        );
        assert!(
            !output.contains("__REGISTRATION_SOURCE")
                && !output.contains("__REGISTRATION_MODULE_NAME"),
            "identity is derived at the declaration site, so nothing is injected: {output}"
        );
        assert!(
            output.contains("mod control;") && output.contains("pub use control::*;"),
            "folder face loads into a same-named child module and re-exports: {output}"
        );
        assert!(
            output.contains("pub mod button;"),
            "leaf face keeps its own module name: {output}"
        );
        assert!(
            !output.contains("pub mod button {"),
            "leaf face must not gain a container module: {output}"
        );
        // rust-analyzer ignores `#[path]` on a `mod` nested inside an inline
        // module, so every nested face needs a crate-root declaration that only
        // the IDE sees. rust-analyzer 会忽略内联模块里 `#[path]`，因此每个嵌套
        // 注册面都需要一条只有 IDE 才看到的 crate 根声明。
        assert!(
            output.contains("#[cfg(not(rust_analyzer))]"),
            "the real declaration yields to the IDE view: {output}"
        );
        assert!(
            output.contains(&format!(
                "#[cfg(rust_analyzer)]\n#[doc(hidden)]\n#[path = {button_path:?}]\npub mod __nichlink_ra_control_object_button;"
            )),
            "leaf face needs a crate-root shadow declaration: {output}"
        );
        assert!(
            output.contains("pub use crate::__nichlink_ra_control_object_button as button;"),
            "the shadow must rebuild the face's public module path: {output}"
        );
        assert!(
            output.contains(&format!(
                "#[cfg(rust_analyzer)]\n#[doc(hidden)]\n#[path = {control_path:?}]\nmod __nichlink_ra_control;"
            )),
            "container face needs the same IDE view at the top level: {output}"
        );
        assert!(
            output.contains("pub(crate) use crate::__nichlink_ra_control as control;"),
            "the container shadow must rebuild its module path: {output}"
        );
        fs::remove_dir_all(root).expect("temporary fixture cleanup");
    }

    /// A top-level leaf face already sits where rust-analyzer applies
    /// `#[path]`, so it must not gain a shadow or a `cfg` gate.
    /// 顶层叶子面本来就位于 rust-analyzer 应用 `#[path]` 的位置，因此不应多出
    /// 影子声明或 `cfg` 开关。
    #[test]
    fn top_level_faces_keep_a_single_declaration() {
        let root = temporary_directory("top-level-face");
        let control = root.join("control.rs");
        write_registry(&control, "root_object", "Control", "crate::ROOT_NODE_ID");
        let nodes = vec![Node {
            name: "control".to_owned(),
            file: Some(control.clone()),
            children: Vec::new(),
        }];

        let output = render_lib(
            &root,
            &nodes,
            &BuildDiagnostics::default(),
            &BuildDiagnostics::default(),
            &SourceScope {
                roots: None,
                reason: "test",
            },
            &[],
            &[],
        );

        assert!(
            output.contains("pub mod control;"),
            "top-level leaf face keeps its declaration: {output}"
        );
        assert!(
            !output.contains("__nichlink_ra_"),
            "a face the IDE already sees needs no shadow: {output}"
        );
        fs::remove_dir_all(root).expect("temporary fixture cleanup");
    }
}
