//! Generated module tree rendering.
//! 生成模块树渲染。

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use super::diagnostics::BuildDiagnostics;
use super::registry_syntax::GraftSyntax;
use super::static_plan::StaticFaceRecord;
use super::types::Node;
use super::{SourceScope, module_feature, node_id, relative_display, source_is_active};

pub(crate) fn render_lib(
    src: &Path,
    nodes: &[Node],
    errors: &BuildDiagnostics,
    demo_errors: &BuildDiagnostics,
    scope: &SourceScope,
    static_faces: &[StaticFaceRecord],
    grafts: &[GraftSyntax],
) -> String {
    let mut output = String::from(
        "// @generated by build.rs; do not edit.\n// 由 build.rs 生成，请勿手工修改。\n\n",
    );
    render_object_aliases(&mut output, src, nodes);
    for node in nodes {
        render_node(&mut output, src, node, 0, scope, false);
    }
    output.push_str("\npub use ::nichlink_run_method::registry_core::*;\n");
    output.push_str(
        "\n#[doc(hidden)]\npub static BUILTIN_STATIC_FACES: &[::nichlink_run_method::registry_core::StaticFace] = &[\n",
    );
    for face in static_faces {
        writeln!(output, "    ::nichlink_run_method::registry_core::StaticFace::new(::nichlink_run_method::registry_core::NodeId::from_raw({:?}), ::nichlink_run_method::registry_core::NodeId::from_raw({:?}), {}),", face.id.into_bytes(), face.parent.into_bytes(), face.owns_registry).unwrap();
    }
    output.push_str("];\n");
    let modules = static_faces
        .iter()
        .map(|face| (face.id, face.module.as_str()))
        .collect::<BTreeMap<_, _>>();
    output.push_str("\n// Registration rules are consumed by const evaluation only.\n// 注册规则只参与常量求值，不进入发布态数据。\n");
    for face in static_faces {
        let rule = modules.get(&face.parent).map_or_else(
            || "::nichlink_run_method::registry_core::RegistrationRule::ANY".to_owned(),
            |parent| format!("{parent}::REGISTRATION.registry_rule"),
        );
        writeln!(
            output,
            "const _: () = ::nichlink_run_method::registry_core::assert_static_registration({rule}, {}::REGISTRATION);",
            face.module
        )
        .unwrap();
    }
    output.push_str(
        "\n#[doc(hidden)]\npub static BUILTIN_GRAFT_CUTS: &[::nichlink_run_method::registry_core::StaticGraftCut] = &[\n",
    );
    for graft in grafts {
        writeln!(
            output,
            "    ::nichlink_run_method::registry_core::StaticGraftCut::new({:?}, {:?}, {}),",
            graft.cut, graft.graft, graft.full
        )
        .unwrap();
    }
    output.push_str("];\n\n");
    output.push_str("pub static BUILTIN_STATIC_PLAN: ::nichlink_run_method::registry_core::StaticPlan = ::nichlink_run_method::registry_core::StaticPlan::with_grafts(BUILTIN_STATIC_FACES, BUILTIN_GRAFT_CUTS);\n\n");
    output.push_str("pub const fn builtin_static_plan() -> &'static ::nichlink_run_method::registry_core::StaticPlan { &BUILTIN_STATIC_PLAN }\n");
    output.push_str("\npub fn registrations() -> Vec<RegistrationInfo> {\n    vec![\n");
    for face in static_faces {
        writeln!(output, "        {}::REGISTRATION,", face.module).unwrap();
    }
    output.push_str("    ]\n        .into_iter()\n        .collect()\n}\n");
    if !errors.is_empty() {
        output.push('\n');
        writeln!(output, "compile_error!({:?});", errors.render()).unwrap();
    }
    if !demo_errors.is_empty() {
        output.push_str("\n#[cfg(feature = \"compile_error_demo\")]\n");
        writeln!(output, "compile_error!({:?});", demo_errors.render()).unwrap();
    }
    output
}

/// Emit one visible declaration macro for every folder-level registry name.
/// 为文件夹级注册机生成对应的可见声明宏。
///
/// The aliases keep the hierarchy in the source (`test1_object!` instead of
/// one anonymous primitive) while forwarding to the one core
/// implementation. Explicit `parent:` fields remain the source of truth.
/// 别名让源码直接表达层级（如 `test1_object!`），同时仍只转发到唯一的
/// 隐藏实现；真正的父子关系仍以显式 `parent:` 字段为准。
fn render_object_aliases(output: &mut String, src: &Path, nodes: &[Node]) {
    let mut names = BTreeSet::from(["root".to_owned()]);
    collect_object_aliases(src, nodes, &mut names);
    for name in names {
        writeln!(
            output,
            "#[doc(hidden)]\n#[allow(unused_macros)]\nmacro_rules! {name}_object {{\n    ($($tokens:tt)*) => {{ ::nichlink_run_method::__nichlink_object! {{ $($tokens)* }} }}\n}}\n#[allow(unused_imports)]\npub(crate) use {name}_object;\n"
        )
        .unwrap();
    }
}

fn collect_object_aliases(src: &Path, nodes: &[Node], names: &mut BTreeSet<String>) {
    for node in nodes {
        let owns_registry = node.file.as_ref().is_some_and(|file| {
            fs::read_to_string(file)
                .ok()
                .and_then(|source| {
                    crate::parsed_face(&source, &relative_display(src, file))
                        .and_then(|face| face.boolean("needs_registry"))
                })
                .unwrap_or(false)
        });
        if owns_registry {
            names.insert(node.name.clone());
        }
        collect_object_aliases(src, &node.children, names);
    }
}

fn render_node(
    output: &mut String,
    src: &Path,
    node: &Node,
    depth: usize,
    scope: &SourceScope,
    selected_ancestor: bool,
) {
    if node
        .file
        .as_ref()
        .is_some_and(|file| relative_display(src, file) == "registry_core/macros/macros.rs")
    {
        return;
    }
    let selected_here = selected_ancestor
        || node_id(src, node).is_some_and(|id| {
            scope
                .roots
                .as_ref()
                .is_some_and(|roots| roots.contains(&id))
        });
    if !scope.includes(src, node, selected_ancestor) {
        return;
    }
    let include_source = source_is_active(src, node, scope, selected_ancestor);
    let indent = "    ".repeat(depth);
    if depth == 0 && node.name == "compile_error_demo" {
        writeln!(output, "{indent}#[cfg(feature = \"compile_error_demo\")]").unwrap();
    }
    if let Some(feature) = module_feature(src, node) {
        writeln!(output, "{indent}#[cfg(feature = {feature:?})]").unwrap();
    }
    writeln!(
        output,
        "{indent}#[allow(dead_code, unused_imports, ambiguous_glob_reexports, clippy::items_after_test_module, clippy::module_inception)]"
    )
    .unwrap();
    // A face file is loaded as a real module through `#[path]`, never through
    // `include!`. That is what lets rust-analyzer resolve the file the author
    // edits, and it is why a face file may keep opening with `//!`: `include!`
    // expansion cannot introduce inner attributes, and `#[path]` on a module
    // with an inline body ignores the path.
    // 注册面文件通过 `#[path]` 以真实模块载入，不再走 `include!`。这正是
    // rust-analyzer 能解析作者正在编辑的文件的原因，也是面文件可以继续以
    // `//!` 开头的原因：`include!` 展开无法引入 inner attribute，而带内联体的
    // 模块上的 `#[path]` 会被忽略。
    //
    // The declaration macros derive `source` from `file!()` and the registry
    // name from `module_path!()`, so no per-face constants are injected here.
    // For a leaf face the file is loaded under its own name, which keeps the
    // public module path unchanged. A face that owns child registries must also
    // be their container, so it loads into a same-named child module and
    // re-exports; only that case gains a module-path segment.
    // 声明宏从 `file!()` 推导 `source`、从 `module_path!()` 推导注册机名，因此
    // 这里不再注入逐面常量。叶子面以自身名字载入，公开模块路径保持不变；拥有
    // 子注册机的面必须同时充当容器，于是载入到同名子模块再重导出——只有这种
    // 情况会多出一段模块路径。
    let absolute = node
        .file
        .as_ref()
        .map(|file| file.to_string_lossy().replace('\\', "/"));
    if let (true, Some(absolute)) = (include_source, absolute.as_ref())
        && node.children.is_empty()
    {
        writeln!(output, "{indent}#[path = {absolute:?}]").unwrap();
        writeln!(output, "{indent}pub mod {};", node.name).unwrap();
        return;
    }
    writeln!(output, "{indent}pub mod {} {{", node.name).unwrap();
    if let (true, Some(absolute)) = (include_source, absolute.as_ref()) {
        let inner = "    ".repeat(depth + 1);
        writeln!(output, "{inner}#[path = {absolute:?}]").unwrap();
        writeln!(output, "{inner}mod {};", node.name).unwrap();
        writeln!(output, "{inner}pub use {}::*;", node.name).unwrap();
    }
    for child in &node.children {
        render_node(
            output,
            src,
            child,
            depth + 1,
            scope,
            selected_ancestor || selected_here,
        );
    }
    if depth == 0 && node.name == "registry_core" {
        let inner = "    ".repeat(depth + 1);
        for child in node.children.iter().filter(|child| child.name != "macros") {
            if let Some(feature) = module_feature(src, child) {
                writeln!(output, "{inner}#[cfg(feature = {feature:?})]").unwrap();
            }
            writeln!(output, "{inner}pub use {}::*;", child.name).unwrap();
        }
    }
    writeln!(output, "{indent}}}").unwrap();
}

#[cfg(test)]
mod tests {
    use super::{render_lib, render_object_aliases};
    use crate::SourceScope;
    use crate::diagnostics::BuildDiagnostics;
    use crate::registry_syntax::GraftSyntax;
    use crate::types::Node;
    use nichlink::registry_core::syntax::SyntaxLocation;
    use std::fs;
    use std::path::{Path, PathBuf};
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn aliases_cover_each_registry_level() {
        let root = temporary_directory("object-aliases");
        let workspace = root.join("workspace/workspace.rs");
        let panel = root.join("workspace/object/panel/panel.rs");
        let control = root.join("control/control.rs");
        write_registry(
            &workspace,
            "root_object",
            "Workspace",
            "crate::ROOT_NODE_ID",
        );
        write_registry(
            &panel,
            "workspace_object",
            "Panel",
            "crate::workspace::NODE_ID",
        );
        write_registry(&control, "root_object", "Control", "crate::ROOT_NODE_ID");
        let nodes = vec![
            Node {
                name: "control".to_owned(),
                file: Some(control),
                children: Vec::new(),
            },
            Node {
                name: "workspace".to_owned(),
                file: Some(workspace),
                children: vec![Node {
                    name: "panel".to_owned(),
                    file: Some(panel),
                    children: Vec::new(),
                }],
            },
        ];

        let mut output = String::new();
        render_object_aliases(&mut output, &root, &nodes);

        assert!(output.contains("macro_rules! root_object"));
        assert!(output.contains("macro_rules! workspace_object"));
        assert!(output.contains("macro_rules! panel_object"));
        assert!(output.contains("macro_rules! control_object"));
        assert!(output.contains("::nichlink_run_method::__nichlink_object!"));
        assert!(output.contains("#[allow(unused_macros)]"));
        assert!(output.contains("#[allow(unused_imports)]"));
        fs::remove_dir_all(root).expect("temporary fixture cleanup");
    }

    #[test]
    fn empty_tree_does_not_emit_a_legacy_control_alias() {
        let root = temporary_directory("empty-object-aliases");
        let mut output = String::new();

        render_object_aliases(&mut output, &root, &[]);

        assert!(output.contains("macro_rules! root_object"));
        assert!(!output.contains("macro_rules! control_object"));
        fs::remove_dir_all(root).expect("temporary fixture cleanup");
    }

    #[test]
    fn generated_static_plan_owns_build_time_graft_selectors() {
        let root = temporary_directory("static-graft-plan");
        let output = render_lib(
            &root,
            &[],
            &BuildDiagnostics::default(),
            &BuildDiagnostics::default(),
            &SourceScope {
                roots: None,
                reason: "test",
            },
            &[],
            &[GraftSyntax {
                cut: "root/control/button".to_owned(),
                graft: "button_fast".to_owned(),
                full: false,
                location: SyntaxLocation { line: 3, column: 5 },
            }],
        );

        assert!(output.contains("StaticPlan::with_grafts"));
        assert!(output.contains("StaticGraftCut::new(\"root/control/button\", \"button_fast\""));
        assert!(!output.contains("pub fn builtin_graft_plan"));
        fs::remove_dir_all(root).expect("temporary fixture cleanup");
    }

    /// Faces load as real modules through `#[path]`, never as copies. A leaf
    /// face keeps its own module name so the public path is unchanged; a face
    /// that owns child registries must also be their container, so it loads
    /// into a same-named child module and re-exports.
    /// 注册面通过 `#[path]` 以真实模块载入，绝不是副本。叶子面保留自身模块名，
    /// 公开路径不变；拥有子注册机的面必须同时充当容器，因此载入同名子模块再
    /// 重导出。
    #[test]
    fn faces_load_by_path_without_copies_or_injected_constants() {
        let root = temporary_directory("path-loaded-faces");
        let control = root.join("control/control.rs");
        let button = root.join("control/object/button/button.rs");
        write_registry(&control, "root_object", "Control", "crate::ROOT_NODE_ID");
        write_registry(
            &button,
            "control_object",
            "Button",
            "crate::control::NODE_ID",
        );
        let nodes = vec![Node {
            name: "control".to_owned(),
            file: Some(control.clone()),
            children: vec![Node {
                name: "object".to_owned(),
                file: None,
                children: vec![Node {
                    name: "button".to_owned(),
                    file: Some(button.clone()),
                    children: Vec::new(),
                }],
            }],
        }];

        let output = render_lib(
            &root,
            &nodes,
            &BuildDiagnostics::default(),
            &BuildDiagnostics::default(),
            &SourceScope {
                roots: None,
                reason: "test",
            },
            &[],
            &[],
        );

        let control_path = control.to_string_lossy().replace('\\', "/");
        let button_path = button.to_string_lossy().replace('\\', "/");
        assert!(
            output.contains(&format!("#[path = {control_path:?}]")),
            "folder face must load its real file: {output}"
        );
        assert!(
            output.contains(&format!("#[path = {button_path:?}]")),
            "leaf face must load its real file: {output}"
        );
        assert!(
            !output.contains("include!("),
            "faces must be modules, not included copies: {output}"
        );
        assert!(
            !output.contains("__REGISTRATION_SOURCE")
                && !output.contains("__REGISTRATION_MODULE_NAME"),
            "identity is derived at the declaration site, so nothing is injected: {output}"
        );
        assert!(
            output.contains("mod control;") && output.contains("pub use control::*;"),
            "folder face loads into a same-named child module and re-exports: {output}"
        );
        assert!(
            output.contains("pub mod button;"),
            "leaf face keeps its own module name: {output}"
        );
        assert!(
            !output.contains("pub mod button {"),
            "leaf face must not gain a container module: {output}"
        );
        fs::remove_dir_all(root).expect("temporary fixture cleanup");
    }

    fn write_registry(path: &Path, macro_name: &str, kind: &str, parent: &str) {
        fs::create_dir_all(path.parent().expect("fixture parent"))
            .expect("temporary fixture directory");
        fs::write(
            path,
            format!(
                "crate::{macro_name}! {{ kind: {kind}, needs_registry: true, parent: {parent}, }}"
            ),
        )
        .expect("temporary registry face");
    }

    fn temporary_directory(label: &str) -> PathBuf {
        crate::registry_identity::freeze_test_namespace();
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock after Unix epoch")
            .as_nanos();
        let path = std::env::temp_dir().join(format!(
            "nichlink-build-{label}-{}-{stamp}",
            std::process::id()
        ));
        fs::create_dir_all(&path).expect("temporary fixture root");
        path
    }
}
