//! Generated by NichLink: build the cross-crate half out of the host package it depends on.
//! 由 NichLink 生成：从它依赖的那个宿主包里构建跨 crate 那一半。

/// The host package's root, as cargo placed it.
fn host_root() -> std::path::PathBuf {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml");
    let output = std::process::Command::new("cargo")
        .args(["metadata", "--format-version", "1", "--manifest-path"])
        .arg(&manifest)
        .output()
        .expect("cargo metadata");
    if !output.status.success() {
        panic!("cargo metadata failed: {}", String::from_utf8_lossy(&output.stderr));
    }
    let text = String::from_utf8(output.stdout).expect("utf-8 metadata");
    let name = format!("\"name\":{:?}", "nichlink-example-partitioned-button");
    let at = text.find(&name).unwrap_or_else(|| panic!("`nichlink-example-partitioned-button` is not a dependency of this facade"));
    let rest = &text[at..];
    let key = "\"manifest_path\":\"";
    let start = rest.find(key).expect("the host's manifest path") + key.len();
    let end = start + rest[start..].find('"').expect("the closing quote");
    std::path::PathBuf::from(&rest[start..end])
        .parent()
        .expect("the host's package root")
        .to_path_buf()
}

fn main() {
    println!("cargo:rerun-if-changed=src");
    let host = host_root();
    println!("cargo:rerun-if-changed={}", host.join("src").display());
    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    nichlink_toolchain::build_method::run_for_partition(
        &host,
        &out,
        "nichlink-example-partitioned-button",
        None,
        true,
    )
    .expect("nichlink");
}
