//! Generated by NichLink: the crate that compiles the cross-crate half of a host's registration tree.
//! Do not edit — the declaration lives in the host's `add_crates.rs`.
//! 由 NichLink 生成：编译宿主注册树跨 crate 那一半的 crate。请勿手工修改——声明住在宿主的
//! `add_crates.rs` 里。

pub const NICHLINK_NAMESPACE: &str = "nichlink-example-partitioned-button";

include!(concat!(env!("OUT_DIR"), "/generated_lib.rs"));
